### PR TITLE
announcements api endpoint

### PR DESCRIPTION
**Pull request by dakriy**
#25 MUST BE MERGED FIRST!

Create an api endpoint for announcements from the database, sample dump:

[{"id":1,"title":"Saepe recusandae illo dolor et dignissimos et.","content":"Sapiente molestiae a totam nobis. Non accusantium molestias facilis neque placeat. Qui illum et nesciunt et vel rerum impedit. Magnam odit perferendis maxime eveniet.","user_id":1,"last_modified_by":1,"created_at":"2018-07-17 04:04:04","updated_at":"2018-07-17 04:04:04"},{"id":2,"title":"Et asperiores aspernatur eius inventore pariatur.","content":"Nihil qui voluptates labore tempore. Ipsam aut laboriosam rem voluptatem. Ut unde deleniti et vel ut sed. Quis quaerat quasi sed unde voluptas nemo nisi.","user_id":2,"last_modified_by":2,"created_at":"2018-07-17 04:04:04","updated_at":"2018-07-17 04:04:04"},{"id":3,"title":"Est qui vel praesentium nobis in et.","content":"Quia qui dolorem omnis recusandae. Et dolore impedit nihil facilis dolore perspiciatis. Eveniet et consectetur tempore magnam enim quia et.","user_id":3,"last_modified_by":3,"created_at":"2018-07-17 04:04:04","updated_at":"2018-07-17 04:04:04"},{"id":4,"title":"Aut omnis et tenetur.","content":"Eius doloremque libero error ipsa quo quis rerum. Laboriosam natus ut id. Sit ut facilis similique qui animi sed mollitia. Qui est ut voluptates et vitae et repudiandae.","user_id":4,"last_modified_by":4,"created_at":"2018-07-17 04:04:04","updated_at":"2018-07-17 04:04:04"},{"id":5,"title":"Dolorem alias ut laboriosam blanditiis autem consequatur.","content":"Ratione eos aut ad voluptatem ipsum qui. Quia nihil perspiciatis asperiores tempora. Praesentium qui aut alias vitae eligendi delectus ex. Labore inventore voluptatem delectus qui ipsum rerum voluptas.","user_id":5,"last_modified_by":5,"created_at":"2018-07-17 04:04:04","updated_at":"2018-07-17 04:04:04"},{"id":6,"title":"Similique autem molestiae temporibus numquam beatae sapiente nam.","content":"Deserunt rerum cupiditate dolorem cupiditate quasi et recusandae autem. Rerum placeat quis molestiae adipisci illum qui. Saepe odio id quia.","user_id":6,"last_modified_by":6,"created_at":"2018-07-17 04:04:04","updated_at":"2018-07-17 04:04:04"},{"id":7,"title":"Rerum quaerat vero distinctio labore.","content":"Nemo voluptatem omnis nihil enim corporis magni et vero. Doloribus error laborum molestias reprehenderit quo. Sit ipsam quia pariatur quod ut et eum.","user_id":7,"last_modified_by":7,"created_at":"2018-07-17 04:04:05","updated_at":"2018-07-17 04:04:05"},{"id":8,"title":"Eum quibusdam quo ut ex voluptatum sunt at.","content":"Libero est et occaecati fuga quos quisquam aut. Amet impedit deleniti ratione sint maiores exercitationem atque. Ut iure eveniet inventore et. Minus beatae perspiciatis magnam illum quia impedit est laboriosam.","user_id":8,"last_modified_by":8,"created_at":"2018-07-17 04:04:05","updated_at":"2018-07-17 04:04:05"},{"id":9,"title":"Hic aliquam veniam ea et.","content":"Illum molestias eligendi sint et laudantium. Consequatur iure optio ea ut fugiat et. Harum reiciendis dolor voluptatibus sunt. Sequi autem quia dolorem.","user_id":9,"last_modified_by":9,"created_at":"2018-07-17 04:04:05","updated_at":"2018-07-17 04:04:05"},{"id":10,"title":"Suscipit iure repellendus dolore nobis alias quaerat voluptas.","content":"Nihil adipisci blanditiis qui id. Asperiores quibusdam reprehenderit minus omnis.","user_id":10,"last_modified_by":10,"created_at":"2018-07-17 04:04:05","updated_at":"2018-07-17 04:04:05"}]

### CODE REVIEW

**Comment by dakriy** [comment]
Yeah that shouldn't be too hard.

**Comment by dakriy** [comment]
@blakestone95 may I ask why though? I mean, doesn't the route/url essentially serve whatever purpose that that key would?

**Comment by blakestone95** [comment]
@dakriy Other endpoints might return multiple objects like this at the same time, at which point we would need this structure.  Doing this preemptively would make sure we're consistent if it ever happens.  Also, I think it helps the front end people tell what they have at a glance.

**Comment by blakestone95** [comment]
@dakriy Are you waiting for something on this PR?

**Comment by dakriy** [comment]
OH, nope. I just didn't see it somehow, I'll get it.

**Pull request merged**
